version: '3.8'

services:
  products:
    build: ./products
    ports:
      - "3001:3001"
  
  orders:
    build: ./orders
    ports:
      - "3002:3002"
    depends_on:
      - db
      - redis

  payments:
    build: ./payments
    ports:
      - "3003:3003"
    depends_on:
      - orders

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"